version: '3.7'
services: 
  database:
    image: mysql:8.0.22
    container_name: learn-cert-database
    restart: always
    environment:
      MYSQL_DATABASE: learn_cert_db
      MYSQL_ROOT_PASSWORD: Root0++
      MYSQL_USER: root
      MYSQL_PASSWORD: Root0++
    ports:
      - '3306:3306'
    volumes:
      - ./tmp/mysql/data:/var/lib/mysql
  api:
    build: '.'
    container_name: learn-cert-api
    ports: 
      - '8080:5000'
    depends_on:
      - database
    healthcheck:
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - DBHOST=database