version: '3.7'
services: 
  api:
    build: '.'
    container_name: learn-cert-api
    restart: always
    ports: 
      - '8080:5000'
networks:
  learn-cert-network:
    name: learn-cert-network
    driver: bridge